### ISSUE TITLE
终于找到个火箭筒专用的EFI了

### ISSUE THREAD

**Issue by asdqian** [Tyrone2333/r5-2600-b450m-bazooka-5700-hackintosh#1]
用的别人迫击炮的EFI。USB 有的没法识别。 试下这个

**Comment by Tyrone2333** [comment]
> 用的别人迫击炮的EFI。USB 有的没法识别。 试下这个

当初图便宜买的这个板子,比迫击炮少了个 m2,pcie 插槽位置也奇葩导致我装不上无线网卡,总之就是非常后悔😭

**Comment by asdqian** [comment]
> > 用的别人迫击炮的EFI。USB 有的没法识别。 试下这个
> 
> 当初图便宜买的这个板子,比迫击炮少了个 m2,pcie 插槽位置也奇葩导致

**Comment by asdqian** [comment]
嗯嗯 我当时自己装机不会写配置。看虎扑推荐的配置配的。等有钱了，直接换英特尔了。

**Comment by asdqian** [comment]
老哥 我发现个问题啊，cpu型号那里显示未知。你config_platforminfo里的处理器值应该改为0，就能识别了。  还有 我机箱前面的usb口还是不行，3.0的口只能识别3.0的u盘。手机啥的都不行。2.0的口供电好像也有问题。  看来我要学学定制usb了。

**Comment by asdqian** [comment]
原来是我搞错了。我的机箱前面板3.0口只能识别3.0的U盘。2.0的估计线不行，供电可能不好。B450M我看有人说不用定制USB。对了 我是4K屏幕。需要把NVRAM里的uiscale改为02.这样在引导界面可以开启HIDPI。你的KEXT里面还有SMCAMD这个。可以看AMD CPU的频率对吧。我试试 能看的话就方便多了

**Comment by Tyrone2333** [comment]
> 原来是我搞错了。我的机箱前面板3.0口只能识别3.0的U盘。2.0的估计线不行，供电可能不好。B450M我看有人说不用定制USB。对了 我是4K屏幕。需要把NVRAM里的uiscale改为02.这样在引导界面可以开启HIDPI。你的KEXT里面还有SMCAMD这个。可以看AMD CPU的频率对吧。我试试 能看的话就方便多了

我是 2k 屏幕,uiscale 我回去试试好使不. 我的前面板 USB 坏了,只有一个 2.0,我也只是连  iPhone 编译 app 用,所以懒得管了.

**Comment by asdqian** [comment]
嗯嗯
