### ISSUE TITLE
正常开机无问题。直接更新bigsur 卡eb了就是你之前说的那个问题 我重建了分区也没用

### ISSUE THREAD

**Issue by Xiaolangs** [Tyrone2333/r5-2600-b450m-bazooka-5700-hackintosh#2]

**Comment by Tyrone2333** [comment]
更新 bigsur 建议要升级一下 oc,我卡现在卖了没法整

**Comment by Xiaolangs** [comment]
> 更新 bigsur 建议要升级一下 oc,我卡现在卖了没法整

我是10.15.7更新出现的。也是oc版本问题吗

**Comment by Tyrone2333** [comment]
我建议是固定版本不要瞎升级系统,没什么用. 你直接下载对应版本刷了看下还会不会有这问题

**Comment by Xiaolangs** [comment]
> 我建议是固定版本不要瞎升级系统,没什么用. 你直接下载对应版本刷了看下还会不会有这问题

因为电脑东西太多 不想重新刷所以才想升级的

**Comment by Tyrone2333** [comment]
玩黑苹果就要有这种升级出错的觉悟 --! 等矿难我换回 A卡再研究
